title: Hello Jekyll Elementor
description: A Jekyll theme inspired by Hello Elementor, with blog support
baseurl: ""
url: ""
markdown: kramdown
paginate: 5
paginate_path: "/page:num"
plugins:
  - jekyll-paginate